//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnvCreationHelmRepo) DeepCopyInto(out *EnvCreationHelmRepo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnvCreationHelmRepo.
func (in *EnvCreationHelmRepo) DeepCopy() *EnvCreationHelmRepo {
	if in == nil {
		return nil
	}
	out := new(EnvCreationHelmRepo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxPullRequestGenerator) DeepCopyInto(out *FluxPullRequestGenerator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxPullRequestGenerator.
func (in *FluxPullRequestGenerator) DeepCopy() *FluxPullRequestGenerator {
	if in == nil {
		return nil
	}
	out := new(FluxPullRequestGenerator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FluxPullRequestGenerator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxPullRequestGeneratorList) DeepCopyInto(out *FluxPullRequestGeneratorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]FluxPullRequestGenerator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxPullRequestGeneratorList.
func (in *FluxPullRequestGeneratorList) DeepCopy() *FluxPullRequestGeneratorList {
	if in == nil {
		return nil
	}
	out := new(FluxPullRequestGeneratorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *FluxPullRequestGeneratorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxPullRequestGeneratorSpec) DeepCopyInto(out *FluxPullRequestGeneratorSpec) {
	*out = *in
	if in.GithubPRRepository != nil {
		in, out := &in.GithubPRRepository, &out.GithubPRRepository
		*out = new(GithubPRRepository)
		(*in).DeepCopyInto(*out)
	}
	if in.EnvCreationHelmRepo != nil {
		in, out := &in.EnvCreationHelmRepo, &out.EnvCreationHelmRepo
		*out = new(EnvCreationHelmRepo)
		**out = **in
	}
	out.Interval = in.Interval
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxPullRequestGeneratorSpec.
func (in *FluxPullRequestGeneratorSpec) DeepCopy() *FluxPullRequestGeneratorSpec {
	if in == nil {
		return nil
	}
	out := new(FluxPullRequestGeneratorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FluxPullRequestGeneratorStatus) DeepCopyInto(out *FluxPullRequestGeneratorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FluxPullRequestGeneratorStatus.
func (in *FluxPullRequestGeneratorStatus) DeepCopy() *FluxPullRequestGeneratorStatus {
	if in == nil {
		return nil
	}
	out := new(FluxPullRequestGeneratorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubPRRepository) DeepCopyInto(out *GithubPRRepository) {
	*out = *in
	if in.TokenSecretRef != nil {
		in, out := &in.TokenSecretRef, &out.TokenSecretRef
		*out = new(SecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubPRRepository.
func (in *GithubPRRepository) DeepCopy() *GithubPRRepository {
	if in == nil {
		return nil
	}
	out := new(GithubPRRepository)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}
