# permissions for end users to view FluxPullRequestGenerators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: FluxPullRequestGenerator-viewer-role
rules:
- apiGroups:
  - prcontroller.ephemeralenv.io.prcontroller.ephemeralenv.io
  resources:
  - FluxPullRequestGenerators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - prcontroller.ephemeralenv.io.prcontroller.ephemeralenv.io
  resources:
  - FluxPullRequestGenerators/status
  verbs:
  - get
